h9_django/i6i6_ForeignKey_Manytomany/app_movie/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.show__movies),
    path('movie/<int:id_movie>/', views.show__movie, name='movie_detail'),
    # path('movie/<slug:slug_movie>/', views.show__movie, name='movie_detail'),
    path('directors/', views.show__directors),
    path('directors/<int:id_director>/', views.show__director, name='director_detail'),
    path('actors/', views.show__actors),
    path('actors/<int:id_actor>/', views.show__actor, name='actor_detail'),
]

h9_django/i6i6_ForeignKey_Manytomany/i6i6_ForeignKey_Manytomany/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_header = 'Наша админка'
admin.site.index_title = 'Наша под админка'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app_movie.urls')),
] + debug_toolbar_urls()

h9_django/i6i6_ForeignKey_Manytomany/app_book/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=70)
    rating = models.IntegerField()

h9_django/i6i6_ForeignKey_Manytomany/app_movie/models.py
from dask.bag.random import choices
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Director(models.Model):
    name_first = models.CharField(max_length=100, default='режиссер_имя')
    name_last = models.CharField(max_length=100, default='режиссер_фамилия')
    director_email = models.EmailField()
    def __str__(self):
        return f'{self.name_first} {self.name_last}'
    def get__url(self):
        return reverse('director_detail', args=[self.id])

class RoomDressing(models.Model):
    floor = models.IntegerField()
    number = models.IntegerField()
    def __str__(self):
        return f'{self.floor} {self.number}'


class Actor(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = {
        MALE: "Мужчина",
        FEMALE: "Женщина",
    }
    name_first = models.CharField(max_length=100, default='актер_имя')
    name_last = models.CharField(max_length=100, default='актер_фамилия')
    gender = models.CharField(max_length=1, choices=GENDERS, default=MALE)
    roomDressing = models.OneToOneField(RoomDressing, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        if self.gender == self.MALE:
            return f'Актер {self.name_first} {self.name_last}'
        else:
            return f'Актриса {self.name_first} {self.name_last}'
    def get__url(self):
        return reverse('actor_detail', args=[self.id])


class Movie(models.Model):
    EUR = 'EUR'
    USD = 'USD'
    RUB = 'RUB'
    CURRENCY_CHOICES = {
        EUR: "Euro",
        USD: "Dollar",
        RUB: "Rubles",
    }
    # id создалось:автоматически
    name = models.CharField(max_length=40)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    year = models.IntegerField(null=True, blank=True)
    budget = models.IntegerField(default=1_000_000, validators=[MinValueValidator(1)])
    slug = models.SlugField(default='', null=True, db_index=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=RUB)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    actors = models.ManyToManyField(Actor)
    def __str__(self):
        return f'{self.name}, {self.rating}'
    def get__url(self):
        return reverse('movie_detail', args=[self.id])
        # return reverse('movie_detail', args=[self.slug])
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Movie, self).save(*args, **kwargs)

h9_django/i6i6_ForeignKey_Manytomany/app_book/views.py
from django.shortcuts import render

# Create your views here.

h9_django/i6i6_ForeignKey_Manytomany/app_movie/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import F, Sum, Max, Min, Count, Avg, Value
from sqlalchemy import nulls_last
from .models import Director, Movie, Actor

def show__movies(request):
    # movies = Movie.objects.order_by(F('year').asc(nulls_first=True))
    movies = Movie.objects.annotate(
        fieldNewBool=Value(True),
        fieldNewBoolFalse=Value(False),
        budgetNew=F('budget')+100,
    )
    agg = movies.aggregate(Avg('budget'), Max('rating'), Min('rating'), Count('name'))
    return render(request, 'app_movie/movies.html', context={
        'movies': movies,
        'agg': agg,
    })

def show__movie(request, id_movie:int):
    movie = get_object_or_404(Movie, id=id_movie)
    return render(request, 'app_movie/movie.html', context={'movie': movie})

# def show__movie(request, slug_movie:str):
#     movie = get_object_or_404(Movie, slug=slug_movie)
#     return render(request, 'app_movie/movie.html', context={'movie': movie})

def show__directors(request):
    directors = Director.objects.all()
    return render(request, 'app_movie/directors.html', context={'directors': directors})

def show__director(request, id_director:int):
    director = get_object_or_404(Director, id=id_director)
    return render(request, 'app_movie/director.html', context={'director': director})

def show__actors(request):
    actors = Actor.objects.all()
    return render(request, 'app_movie/actors.html', context={'actors': actors})

def show__actor(request, id_actor:int):
    actor = get_object_or_404(Actor, id=id_actor)
    return render(request, 'app_movie/actor.html', context={'actor': actor})

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/actor.html
{% extends 'app_movie/base.html' %}

{% block title %} Информация_актера {{actor.name_first}} {% endblock title%}
{% block content %}
  <h2>name_first = {{actor.name_first}}</h2>
  <h3>name_last = {{actor.name_last}}</h3>
  <h3>gender = {{actor.gender}}</h3>
  <hr>
  {% if actor.gender == 'F' %}
        <h3>Пол: женский</h3>
    {% else %}
        <h3>Пол: мужской</h3>
    {% endif %}
  <hr>
  <h3>Фильмы</h3>
  <ul>
    {% for movie in actor.movie_set.all %}
    <li><a href="{{movie.get__url}}">{{movie}}</a></li>
    {% endfor %}
  </ul>
{% endblock content%}

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/actors.html
{% extends 'app_movie/base.html' %}

{% block title %} Все-актеры {% endblock title%}
{% block content %}
  <h2>Список_актеры</h2>
  <ul>
    {% for actor in actors %}
      <li><a href='{{actor.get__url}}'>{{actor.name_first}}</a>,
        name_last = {{actor.name_last}},
        gender = {{actor.gender}}
      </li>
    {% endfor %}
  </ul>
{% endblock content%}

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title%}</title>
</head>
<body>
  {% block content %} {% endblock content%}
</body>
</html>

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/director.html
{% extends 'app_movie/base.html' %}

{% block title %} Информация_режиссера {{director.name_first}} {{director.name_last}} {% endblock title%}
{% block content %}
  <h2>Режиссер = {{director.name_first}} {{director.name_last}}</h2>
  <h3>{{director.director_email}}</h3>

  <h3>Фильмы</h3>
  <ul>
    {% for movie in director.movie_set.all %}
    <li><a href="{{movie.get__url}}">{{movie}}</a></li>
    {% endfor %}
  </ul>
{% endblock content%}

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/directors.html
{% extends 'app_movie/base.html' %}

{% block title %} Все-режиссеры {% endblock title%}
{% block content %}
  <h2>Список_режиссеров</h2>
  <ul>
    {% for director in directors %}
      <li><a href='{{director.get__url}}'>{{director.name_first}} {{director.name_last}}</a></li>
    {% endfor %}
  </ul>
{% endblock content%}

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/movie.html
{% extends 'app_movie/base.html' %}

{% block title %} Информация_фильма {{movie.name }} {% endblock title%}
{% block content %}
  <h2>Информация_фильма = {{movie.name}}</h2>
  <h3>Рейтинг = {{movie.rating}}</h3>
  <h3>Бюджет = {{movie.budget}}</h3>
  <h3>Год = {{movie.year}}</h3>
  <hr>
  <h3>Информация_режиссера</h3>
  <h4>Имя {{movie.director.name_first}}</h4>
  <h4>Фамилия {{movie.director.name_last}}</h4>
  <h4>Email {{movie.director.director_email}}</h4>
  <hr>
  <h3>Актеры</h3>
  <ul>
    {% for actor in movie.actors.all %}
    <li><a href="{{actor.get__url}}">{{actor}}</a></li>
    {% endfor %}
  </ul>


{% endblock content%}

h9_django/i6i6_ForeignKey_Manytomany/app_movie/templates/app_movie/movies.html
{% extends 'app_movie/base.html' %}

{% block title %} Все-фильмы {% endblock title%}
{% block content %}
  <h2>Список_фильмов</h2>
  <ul>
    {% for movie in movies %}
      <li><a href='{{movie.get__url}}'>{{movie.name}}</a>,
        рейтинг = {{movie.rating}},
        бюджет = {{movie.budget}},
        год = {{movie.year}}
      </li>
    {% endfor %}
  </ul>
  <h3>бюджет:средний = {{agg.budget__avg}}</h3>
  <h3>рейтинг:минимальный = {{agg.rating__max}}</h3>
  <h3>рейтинг:максимальный = {{agg.rating__min}}</h3>
  <h3>всего-фильмов = {{agg.name__count}}</h3>
  <hr>
  <h3>Режиссеры <a href='{{movie.director.get__url}}'>{{movie.director.objects.all}}</a></h3>
  <h3>Актеры </h3>
{% endblock content%}